name: Build

on:
  push:
    branches:
      - source

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Init submodule
      run: |
        git submodule update --init --recursive

    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7

    - name: Install dependencies
      run: |
        cd ./Maverick
        python -m pip install --upgrade pip
        pip install -r prod_req.txt

    # Get build cache
    - uses: actions/checkout@v2
      with:
        ref: 'cache'
        path: './build_cache'

    - name: Build site
      run: |
        # 复用图片解析缓存
        mkdir ./Maverick/cached_imgs
        cp ./build_cache/sizeinfo.json ./Maverick/cached_imgs
        rm -rf ./build_cache/.git

        cd ./Maverick
        python ./build.py -c "../conf.py"

        # 保存图片缓存
        cd ..
        cp ./Maverick/cached_imgs/sizeinfo.json ./build_cache

    - name: Deploy to GitHub Pages
      uses: docker://peaceiris/gh-pages:v2
      env:
        PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: ./dist
      with:
        emptyCommits: false

    - name: Save build cache
      uses: docker://peaceiris/gh-pages:v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PUBLISH_BRANCH: cache
        PUBLISH_DIR: ./build_cache
      with:
        emptyCommits: false
        
    - name: Deploy static to Tencent CloudBase
      id: deployStatic
      uses: TencentCloudBase/cloudbase-action@v1.1.0
      env:
        PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
        PUBLISH_BRANCH: master
        PUBLISH_DIR: ./dist
      with:
        secretId: ${{ secrets.SECRET_ID }}
        secretKey: ${{ secrets.SECRET_KEY }}
        envId: ${{ secrets.ENV_ID }}
        staticSrcPath: dist
        
    - uses: actions/checkout@v2
    - name: 设置提交者的个人信息
      # 这三个变量的值都放在 https://github.com/oscar-yyc/HexoSource/settings/secrets
      env:
        # 设置时区
        TZ: Asia/Shanghai
        # 在 https://mingwolf.coding.net/user/account/setting/tokens 新建秘钥
        coding_token: ${{ secrets.coding_token }}
        # 团队中的某个人的用户名，一般默认是本人手机号码
        coding_username: ${{ secrets.coding_USERNAME }}
        # 格式为：e.coding.net/组织名/项目名/仓库名.git
        coding_ref: ${{ secrets.coding_REF }}
      run: |
        cd ./dist
        git config --local user.email "iloveyichen"
        git config --local user.name "oscar-yyc"
        git config core.filemode false
        git remote set-url origin https://${coding_ref}
        git add .
        git commit -m "$message"
        git push --force --quiet "https://${coding_username}:${coding_token}@${coding_ref}" gh-pages:master
